name: values_common_editor_flutter
description: GUI editor for values common .html files..

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^4.3.1
  syncfusion_flutter_sliders: ^19.4.42
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^1.0.1
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true